[package]
name = "proc-macro"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc-macro-derive", "proc-macro-core"]

[dependencies]
proc-macro-derive = { version = "0.1.0", path = "proc-macro-derive" }
