[package]
name = "proc-macro-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-core = { version = "0.1.0", path = "../proc-macro-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

